sudo: required

language: minimal

services:
  - docker

script:
- docker build -t steinko/timelogingfuntionalsystemtest .

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
